### ISSUE TITLE
Backend API - DB Not Migrated

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-docker-nodejs-react#1]
registration & signIN actions bump errors: 

```log
node-server    | (node:19) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_ERROR: no such table: user
node-server    |     at new QueryFailedError (/usr/src/app/node_modules/typeorm/error/QueryFailedError.js:12:28)
node-server    |     at handler (/usr/src/app/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:77:38)
node-server    |     at replacement (/usr/src/app/node_modules/sqlite3/lib/trace.js:25:27)
node-server    |     at Statement.errBack (/usr/src/app/node_modules/sqlite3/lib/sqlite3.js:14:21)
node-server    | (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by app-generator** [comment]
Hello @JK-0 

The migration still not working in the latest release. 
I follow the set up as described on the readme: 

- `git clone ...`
- `docker-compose up --build `
- `migrate DB`
  - `docker-compose run --rm node-server yarn typeorm migration:run` 
- Visit `http://127.0.0.1:3000` in browser 

The CLI bumps errors:

```log
UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_ERROR: no such table: user
```
